### ISSUE TITLE
Tiempo

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#101]
Quisiera saber si el sistema tiene un periodo de tiempo? 
Por que después de revisar el contrato (experiencia comercial) regrese ala pestaña de experiencias comerciales para diligenciar los datos que me faltaban,  y me había borrado los datos diligenciados con anterioridad.
Me parece que si tiene tiempo no debería puesto que el revisar un contrato u orden de compra lleva tiempo.

**Comment by SebasDeveloper** [comment]
No tiene ningún temporizador, no se pudo replicar el error.
