### ISSUE TITLE
CÓDIGOS ICA

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#102]
![image](https://cloud.githubusercontent.com/assets/10640094/5962117/69bb636c-a7af-11e4-89a4-785aef979257.png)

Deberían estar todos los códigos del ICA para buscar con mas facilidad tal y como esta en PAR.

**Comment by Davidmt89** [comment]
se agregan todos los códigos del ICA
