### ISSUE TITLE
Experiencias

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#104]
Debería haber una restricción en las fechas de las experiencias comerciales para que no deje ingresar en la fecha final una fecha menor a la inicial.

![image](https://cloud.githubusercontent.com/assets/9558870/5963859/cf702de2-a7bd-11e4-9eec-59ebe7261c70.png)

**Comment by SebasDeveloper** [comment]
Es importante que al momento de hacer el cargue de la información, se garantice la veracidad de la misma, sin embargo se tiene en cuenta la apreciación dado que el margen de error existe.
