### ISSUE TITLE
Certificaciones

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#105]
en la pestaña certificaciones el campo para adjuntar imagen al darle click no abre nada ni permite ingresar.

![image](https://cloud.githubusercontent.com/assets/9558870/5964011/d6bab1de-a7be-11e4-9c51-ccbad8f23e0e.png)

**Comment by SebasDeveloper** [comment]
Esto sucede porque, estas en una columna obligatoria (Alcance) y se supone que no debe dejarte salir de ahí sin que hallas escrito el valor.
