### ISSUE TITLE
ARL

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#107]
Al momento de darle guardar en el campo del ARL borra los datos de la grilla que pertenece a certificación de accidentalidad.

![image](https://cloud.githubusercontent.com/assets/9558768/5964643/bc22d748-a7c3-11e4-98d8-36099f838892.png)

**Comment by SebasDeveloper** [comment]
Recuerda que se mencionó en la capacitación que las pantallas que contiene un formulario y una grilla, necesitan un guardado independiente, es decir que, la grilla necesita guardar y el formulario también con su respectivo botón.
