### ISSUE TITLE
ARL

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#108]
Al momento de darle guardar en el campo del ARL borra los datos de la grilla que pertenece a certificación de accidentalidad.Me parece que los campos deben estar completos en cuanto ala escritura. (la casilla en azul)
![image](https://cloud.githubusercontent.com/assets/9558768/5964643/bc22d748-a7c3-11e4-98d8-36099f838892.png)

![image](https://cloud.githubusercontent.com/assets/9558768/5964699/3512a700-a7c4-11e4-876b-a9b17bafc41d.png)

**Comment by SebasDeveloper** [comment]
Recuerda que se mencionó en la capacitación que las pantallas que contiene un formulario y una grilla, necesitan un guardado independiente, es decir que la grilla necesita guardar y el formulario también con su respectivo botón.
