### ISSUE TITLE
RUT

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#110]
en el campo RUT donde da la opción de dar si es gran contribuyente o autorretenedor debería ser como un check no un campo de habilitar, adicional mente no me esta dejando modificar ese campo.

![image](https://cloud.githubusercontent.com/assets/9558870/5964966/72f7776a-a7c6-11e4-8736-cb8e1be14c8a.png)

**Comment by Davidmt89** [comment]
se soluciona el problema con los campos de gran contribuyente, autorretenedor e iva.
