### ISSUE TITLE
Mejora para el módulo de gestión documental certificado arl

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#112]
Hola muchachos, sucede que observé que se tomó este diseño de PAR con respecto al certificado de accidentalidad: 

![image](https://cloud.githubusercontent.com/assets/9558615/6008188/9f7bd50e-aaed-11e4-9e2d-eff387352d2e.png)

En el módulo de gestión documental se recauda solo el archivo pero no con las especificaciones que nosotros necesitamos.

Así:

![image](https://cloud.githubusercontent.com/assets/9558615/6008401/2ed154b2-aaef-11e4-9e26-6453df7824bb.png)

Se podrían agregar estas especificaciones, ya que si nosotros le solicitamos el "Certificado de Accidentalidad" ellos tienen la posibilidad de hacer una consulta de la información parcial de un año, mientras que si se les solicita en el formulario que la información debe contener esas especificaciones (Horas hombre trabajadas por año, fatalidades por año, número total de incidentes reportados excluyendo accidentes incapacitantes por año, número de accidentes incapacitantes por año, días de incapacidad por año) ellos deberían hacer la solicitud a la ARL para que les certifique esa información y podría ser de utilidad mayor para el cliente.

Todo con el fin de que el formato sea de mayor utilidad a que solo un lugar en el que se anexa un archivo como en PAR.

Anexo otros pantallazos de como son los certificados.

Ejemplo de como necesitamos un certificado de accidentalidad.
![image](https://cloud.githubusercontent.com/assets/9558615/6008487/faedfe1a-aaef-11e4-8480-bb04cd9343fd.png)

Ejemplo de como expide la ARL el certificado y por lo general nos lo envían así.
![image](https://cloud.githubusercontent.com/assets/9558615/6008506/1e046e84-aaf0-11e4-807d-f6b86f6bc904.png)

**Comment by Davidmt89** [comment]
recuerda que el formulario para recibir esa documentación lo crean ustedes, por lo tanto tienes que transmitirle esa duda a Carolina para que valide el tema.
