### ISSUE TITLE
Mejora Dirección

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#113]
![image](https://cloud.githubusercontent.com/assets/9558615/6080456/8429c1f4-addf-11e4-81ce-00f36f3f467a.png)

Por favor no olvidar anexar dirección a la información básica.

**Comment by luixg11** [comment]
Si se le puede anexar la latitud y longitud mucho mejor porque podría anexarse el mapa 
10°24'04.2"N 75°33'19.4"W

**Comment by SebasDeveloper** [comment]
Recuerda que eso va en sucursales
