### ISSUE TITLE
Error al guardar experiencias cambia el valor de pesos a dolares 

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#115]
![image](https://cloud.githubusercontent.com/assets/9558615/6080805/691a69ce-ade2-11e4-9a45-b0a2be6fada3.png)

Cuando le doy guardar me hace la conversión

![image](https://cloud.githubusercontent.com/assets/9558615/6080826/9cf13174-ade2-11e4-917c-2c5c193fd00e.png)

Yo no di esta orden

**Comment by SebasDeveloper** [comment]
Recuerda que siempre se convierte a Dolares, que es la moneda estándar de nuestra herramienta, si el valor está bien cargado en pesos te muestra el valor de acuerdo a la TRM almacenada en el sistema, en  MarketPlace la moneda se muestra como la necesite el comprador
