### ISSUE TITLE
Error en la maestra de las experiencias

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#116]
Sucede que estoy buscando una actividad que se llama "Mantenimiento y Reparación de Equipos" sola, sin ninguna especificación alguna, pero no me aparece.

![image](https://cloud.githubusercontent.com/assets/9558615/6080864/f258e3dc-ade2-11e4-8cc2-ec42cdbcee57.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6080877/0c84291a-ade3-11e4-9262-3b1fae98aa97.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6080888/145cb83c-ade3-11e4-97fa-4a5fdf81c6b5.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6080893/1feaaf2e-ade3-11e4-8b4e-8362485811de.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6080901/319e9460-ade3-11e4-9225-38fdef56825f.png)

Anexo muchos pantallazos para que puedan observar que no se encuentra la actividad, además acorde a lo sugerido debería poder escribir "mantenimiento y ..." y no así "mantenimientoy" es decir poder escribir y adicionar un espacio sin que el filtro enloquezca.

![image](https://cloud.githubusercontent.com/assets/9558615/6080926/6417b2be-ade3-11e4-8fa9-91b79f845a0c.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6080928/6bf1657a-ade3-11e4-999d-22179b90559a.png)

En este último pantallazo estoy intentando dar espacio pero no me deja.

**Comment by SebasDeveloper** [comment]
Realmente el error es el no poder dar espacio, el hecho de que no se encuentre la actividad que buscas es porque no se ha cargado desde la pantalla que lo administra.
