### ISSUE TITLE
SE CAMBIA EL TIPO DE MONEDA 

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#117]
![image](https://cloud.githubusercontent.com/assets/10640094/6081591/d66894e6-ade8-11e4-8574-6a2a47f66b94.

Deja cambiar el tipo de moneda, pero al guardar la info se cambia y queda en dolares.

**Comment by SebasDeveloper** [comment]
Recuerda que nuestra moneda default es el US por lo tanto cuando tu ingresas el valor en una moneda diferente el hace el calculo y lo cambia, todo esto por temas de estándar.
