### ISSUE TITLE
Error al guardar información de socios

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#122]
![image](https://cloud.githubusercontent.com/assets/9558615/6082426/75150e70-adef-11e4-87aa-fc816701d4d9.png)

**Comment by luixg11** [comment]
despues de que doy click en guardar se me quita la selección y me sale "seleccione una opción"
![image](https://cloud.githubusercontent.com/assets/9558615/6082478/d385735a-adef-11e4-9cf8-81b65e3dbf93.png)

**Comment by Davidmt89** [comment]
se soluciona el problema de socios
