### ISSUE TITLE
Certificados de incapacidad

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#124]
en la pestaña de NUMERO TOTAL DE IN.... deberia hacerse mas pequeñas las letras o acomodar para que salga totalmente lo que quiere decir.
![image](https://cloud.githubusercontent.com/assets/10758646/6082859/4a642bc2-adf2-11e4-85ae-73c1d1e0f238.png)

**Comment by Davidmt89** [comment]
se ajusta el tamaño de las columnas para poder ver el título.
