### ISSUE TITLE
Error que el proveedor nos reporta

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#125]
![image](https://cloud.githubusercontent.com/assets/9558615/6147896/34ce9f46-b1ca-11e4-9d2a-eb6285bf0718.png)

Hola muchachos, el proveedor TECNOLOGIAS AMBIENTALES DE COLOMBIA S.A. ESP nos reporta este error, el nit es 8050015385.

**Comment by SebasDeveloper** [comment]
Pendiente por validar con el proveedor ya que al validar acá, todo funciona bien.

**Comment by luixg11** [comment]
Me comuniqué con el proveedor me dice que va a intentar ingresar de nuevo, le pedí que validara con su área de sistemas debido a que la problemática no es el link.

**Comment by SebasDeveloper** [comment]
Quedo atento a cualquier novedad.
Gracias
