### ISSUE TITLE
Contacto principal de la empresa

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#127]
![image](https://cloud.githubusercontent.com/assets/9386020/6257110/827c7f62-b78b-11e4-9a54-86e54c488f6d.png)

1. Debería llamarse "Contactos de información" algo así.
2. No debería aparecer visible en Market Place ya que esto es informativo para operaciones.
3. En esta pestaña si debería ir el nombre de primero.
3. Cambiar Valor por información.

**Comment by SebasDeveloper** [comment]
Se realizaron los ajustes sugeridos
