### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#130]
Al subir el logo de la empresa y se le da guardar, el logo queda visible en la pantalla.
![image](https://cloud.githubusercontent.com/assets/10758646/6287597/b3594f7e-b8e0-11e4-8694-ceeaf3c342a6.png)

Pero al darle siguiente,  el logo ya no es visible 
![image](https://cloud.githubusercontent.com/assets/10758646/6287642/02af8476-b8e1-11e4-9363-67e316fa0841.png)

**Comment by SebasDeveloper** [comment]
se soluciono correctamente
