### ISSUE TITLE
Error al guardar las certificaciones en la pestaña HSEQ

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#133]
![image](https://cloud.githubusercontent.com/assets/9558615/6289142/ee2f3fd6-b8eb-11e4-9f5d-25f21aeb53ad.png)

Quizá el error se de por darle guardar dos veces pero no puedo asegurarlo.

**Comment by SebasDeveloper** [comment]
es probable, voy a validarlo

**Comment by SebasDeveloper** [comment]
Se le dió gurdar dos veces
