### ISSUE TITLE
Error logo

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#134]
![image](https://cloud.githubusercontent.com/assets/9558615/6289680/bc7defba-b8ef-11e4-8f35-7b71fcb4bf36.png)

Cuando le doy a ver archivo, me sale el siguiente error:

![image](https://cloud.githubusercontent.com/assets/9558615/6289684/c8057d94-b8ef-11e4-84c0-f497e34dba25.png)

**Comment by SebasDeveloper** [comment]
se soluciono correctamente
