### ISSUE TITLE
ERROR EN ESTADOS FINANCIEROS

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#136]
![image](https://cloud.githubusercontent.com/assets/10640094/6290120/99e86e8c-b8f2-11e4-82cc-5c41df548ffc.png)

Al guardar el estado financiero aparece un error, los valores que ingrese son exactamente los mismos que aparecen en el estado financiero de PAR, igualmente lo revise por segunda vez pero no digité algún valor de manera errónea así que debe haber algún problema al dar la opción de guardar.

**Comment by SebasDeveloper** [comment]
se soluciono correctamente
