### ISSUE TITLE
Mejora en pantalla market place/información comercial/experiencias

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#141]
Muchachos, en lo personal creo que en ves de repetirse todas las actividades, debería aparecer una actividad y sus respectivos datos. Como lo hace PAR SERVICIOS pero con una mejor presentación. Recomiendo además que si se fuera a hacer así, se hiciera por orden cronológico, es decir, experiencias mas actuales a las mas antiguas.

Primero anexo el pantallazo de como lo hace par, y luego anexo el pantallazo de como lo tenemos en market place.

![image](https://cloud.githubusercontent.com/assets/9558615/6535118/6172bdc2-c410-11e4-9408-fb3c8357d1a2.png)

![image](https://cloud.githubusercontent.com/assets/9558615/6534994/8c8a2096-c40f-11e4-9d26-3ace2e497fd1.png)

**Comment by SebasDeveloper** [comment]
Se solucionó correctamente
