### ISSUE TITLE
Creación de siguimiento

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#143]
Los clientes no están asociados para los seguimientos
![image](https://cloud.githubusercontent.com/assets/9558768/6536637/5f1d476a-c41d-11e4-865c-1415ff86b4e2.png)
![image](https://cloud.githubusercontent.com/assets/9558768/6536656/82df8f96-c41d-11e4-8504-655872d3a856.png)

**Comment by SebasDeveloper** [comment]
Se soluciono correctamente
