### ISSUE TITLE
Mejora MarketPlace / Información Legal / RUT

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#146]
![image](https://cloud.githubusercontent.com/assets/9558615/6537505/4c210dd8-c425-11e4-81a6-29b2eadafa99.png)

Debería aparecer que no es Gran Contribuyente.

**Comment by luixg11** [comment]
![image](https://cloud.githubusercontent.com/assets/9558615/6622324/f17e5578-c8a9-11e4-9ba7-9984e69442d9.png)
![image](https://cloud.githubusercontent.com/assets/9558615/6622327/f459aa40-c8a9-11e4-8db1-bbccae593ae0.png)

Sebas lo que le comentaba que en market place no me sale si es o no gran contribuyente.

**Comment by SebasDeveloper** [comment]
Se han resuelto todos los Issues
