### ISSUE TITLE
Error en links y contraseñas

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#147]
Buenos días muchachos, 

Encontramos un problema, sucede que un proveedor envió información, pero cuando validamos la información, no era la información del proveedor. Sucede que encontramos información de Corel y Cia S.A. en el link del Instituto Colombiano de Derecho Tributario y encontramos que se puede ingresar al link del Instituto Colombiano de Derecho Tributario con el NIT de Corel y Cia S.A. Además encontramos que en los proveedores de POLIPROPILENO DEL CARIBE, se puede ingresar con el NIT de cualquier proveedor.

8600157644 INSTITUTO COLOMBIANO DE DERECHO TRIBUTARIO Link: https://www.proveedoresonline.co/Registro/ProviderForm?ProviderPublicId=53ACE72C&FormPublicId=F393FCBD

8600246540 COREL Y CIA S.A. Link https://www.proveedoresonline.co/Registro/ProviderForm?ProviderPublicId=11482764&FormPublicId=F393FCBD

**Comment by SebasDeveloper** [comment]
Se soluciono correctamente
