### ISSUE TITLE
2 errores 

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#148]
El primero es que el logo en marketplace se me descuadra.
![image](https://cloud.githubusercontent.com/assets/9558615/6619686/eff146f8-c899-11e4-9255-fe4e0f7f9fd4.png)

El segundo es que la pestaña no sale proveedores sino "proeedor"
![image](https://cloud.githubusercontent.com/assets/9558615/6619702/07b005c2-c89a-11e4-9506-fd15ac79ca95.png)

**Comment by SebasDeveloper** [comment]
Se esta solucionando

**Comment by SebasDeveloper** [comment]
Se solucionó correctamente
