### ISSUE TITLE
Mejoras BACKOFFICE

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#149]
En la reunión del día 11-03-2015 encontramos las siguientes mejoras.

1. Campo fechas Cámara de Comercio.
2. Revisar representante el Sucursales.
3. Revisar Campo Dirección
4. Revisar indicativos en sucursales agregar ejemplo.
5. Campo autorretenedor aun tiene el campo RECIBO 
6. Campo Sarlaft revisar que queden todas de la mas reciente a la mas antigua.
7. Revisar Estructura Organizacional.

Algunas de estas mejoras por favor hablarlas con carolina.

**Comment by SebasDeveloper** [comment]
Se soluciono correctamente
