### ISSUE TITLE
Error MarketPlace/BackOffice

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#153]
En market place me deja ver algo que en BackOffice parametrise que no lo dejara ver y esto me sucede

Market Place:
![image](https://cloud.githubusercontent.com/assets/9558615/6628651/41ba4be8-c8d5-11e4-854e-e539b0eea6b1.png)

Back Office:
![image](https://cloud.githubusercontent.com/assets/9558615/6628655/4e7ae180-c8d5-11e4-834a-48a7cb9e801e.png)

La empresa es COMPUREDES S.A. NIT 8000424718

**Comment by SebasDeveloper** [comment]
Se solucionó correctamente
