### ISSUE TITLE
Aún sale Proeedor

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#154]
Sigue saliendo proeedor en las pestañas que comenté de todos modos indico,

Proeedor sale en la pestaña de Back Office/Información General/Información Básica

![image](https://cloud.githubusercontent.com/assets/9558615/6666733/4071e952-cbb5-11e4-9f3d-d70b2d8e3d9e.png)

Al igual que en k de contratación  Back Office/Información Legal/K de Contratación

![image](https://cloud.githubusercontent.com/assets/9558615/6666751/70090182-cbb5-11e4-8f6e-e6fe14bf5e8a.png)

**Comment by SebasDeveloper** [comment]
Se solucionó correctamente
