### ISSUE TITLE
RUT MARKETPLACE

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#155]
Esto fue lo que reporto Luis.

Te envío un pantallazo de como se está viendo la pestaña del registro único tributario, por favor hacer la observación a los compañeros de tecnología para que la pestaña tenga una pantalla mas ordenada porque así se ve muy feo, además que corrijan las partes de autorretenedor recibo

![image](https://cloud.githubusercontent.com/assets/9558870/6671166/86052eea-cbd1-11e4-82e0-755e956ec427.png)

**Comment by SebasDeveloper** [comment]
Se realizó el ajuste sugerido

**Comment by DianaTibata** [comment]
aun no se ve el cambio del titulo de rut donde aparezca el numero ica y la actividad.

**Comment by SebasDeveloper** [comment]
Solo era caché de la máquina
