### ISSUE TITLE
balances financieros

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#186]
en los estados financieros 2012 aparece en ceros.

![estados financieros](https://cloud.githubusercontent.com/assets/9558870/6814772/b25172cc-d24f-11e4-98f9-6ecca4a79add.png)

**Comment by Josexandthecity** [comment]
El error no esta presente en la versión de desarrollo, por lo que puede producirse debido a un problema al momento de hacer el paso de versión a producción.

**Comment by Josexandthecity** [comment]
Se decidió no reorganizar las columnas del último balance, ya que los items traen la información agrupada y al reorganizarlas la ultima columna quedaría en la mitad.
