### ISSUE TITLE
Mejoras Proveedores Online

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#195]
![image](https://cloud.githubusercontent.com/assets/9386020/7097490/9c1fa420-df9b-11e4-9cf3-151e92fc57b8.png)

![image](https://cloud.githubusercontent.com/assets/9386020/7097499/b1718a1e-df9b-11e4-8e3a-84eeb56652e8.png)

![image](https://cloud.githubusercontent.com/assets/9386020/7097508/be4d138e-df9b-11e4-97d7-78414cf05069.png)

![image](https://cloud.githubusercontent.com/assets/9386020/7097515/cb14c792-df9b-11e4-9377-10145be0dac1.png)

![image](https://cloud.githubusercontent.com/assets/9386020/7097520/d784829c-df9b-11e4-936d-de4604d60fd2.png)

![image](https://cloud.githubusercontent.com/assets/9386020/7097524/e2134fae-df9b-11e4-8db1-f0e72efaa1b7.png)

**Comment by Davidmt89** [comment]
No aplica
