### ISSUE TITLE
Error al crear un proveedor

### ISSUE THREAD

**Issue by yeimylizethgu** [PublicarNuevosNegocios/ProveedoresOnLine#198]
![image](https://cloud.githubusercontent.com/assets/10640191/7170195/865c1674-e391-11e4-9e9b-9fadb26a7e47.png)
 
![image](https://cloud.githubusercontent.com/assets/10640191/7170207/9617e534-e391-11e4-962c-9fc7d47770ef.png)

**Comment by Davidmt89** [comment]
Se solucionó el problema con el registro del proveedor.
