### ISSUE TITLE
Asignación de Usuarios

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#201]
Los siguientes son los ajustes que se deben realizar para la asignación de usuarios:
1. Ingresar el NIT del proveedor
2. Cambiar el orden de las columnas de la siguiente manera:
* NIT
* Cambiar el nombre Proveedor por Razón Social
* Cambiar Certificador por Analista de Validación
* Fecha de Edición
* Id Back Office
* Id Document Management

**Comment by CarlosPinzon** [comment]
Se ajustará con la nueva versión del gestor documental.
