### ISSUE TITLE
Imágenes 

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#202]
![image](https://cloud.githubusercontent.com/assets/9386020/7401451/baea63ac-ee89-11e4-9b9c-59834d10a795.png)

Cuando una empresa no cuenta con logo y se da guardar queda con un cuadrito (Pantallazo), debería aparecer el logo de proveedores Online (pienso yo)

**Comment by Josexandthecity** [comment]
Solucionado en Marketplace y BackOffice
