### ISSUE TITLE
error marketplace

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#208]
en marketplace se esta generando error al momento de buscar un proveedor 
https://www.proveedoresonline.co/Marketplace/Provider/GIProviderInfo?ProviderPublicId=1D89BD4A

**Comment by Josexandthecity** [comment]
NIT: 804355160

No tiene camara de comercio -> en Marketplace da error
Model.RelatedLegalInfo.FirstOrDefault().CP_InscriptionNumber : NullReference

**Comment by Josexandthecity** [comment]
Solucionado
