### ISSUE TITLE
Resumen información HSEQ

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#213]
En el resumen de Información HSEQ, en todas las normas debería aparecer si no cuenta con esta información.  
En OHSAS 18001 aparece un NO, lo mismo debería aparecer en Guia RUC-CCS

![image](https://cloud.githubusercontent.com/assets/9386020/7780411/3d6c9788-00a4-11e5-89e7-3dd85fc92202.png)

**Comment by Josexandthecity** [comment]
Ahora aparece la frase:  No Tiene archivo de certificación
