### ISSUE TITLE
Información Legal - Cámara de comercio

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#214]
En la cámara de comercio el objeto social debería tener mas caracteres ya que algunas veces aparece cortado el texto

![image](https://cloud.githubusercontent.com/assets/9386020/7945060/f22e0cd2-0933-11e5-95c8-4128ea7930d8.png)

**Comment by Josexandthecity** [comment]
Solucionado tanto en MP como en BO y en la base de datos.
