### ISSUE TITLE
Información financiera 

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#215]
En el balance general, al momento de consultar el año 2012 debería aparecer de primer (2012 y 2011) esto con el fin de realizar el análisis vertical y horizontal

![image](https://cloud.githubusercontent.com/assets/9386020/7945254/207b2808-0935-11e5-97d0-25b77ca87fef.png)

**Comment by Josexandthecity** [comment]
Este es el mismo 186
