### ISSUE TITLE
INFORMACIÓN HSEQ

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#218]
En la pestaña de Sistema de riesgos laborales debería aparecer la formula del LTIF

![image](https://cloud.githubusercontent.com/assets/9386020/7945752/5324de22-0938-11e5-879a-a053198a834e.png)

**Comment by Josexandthecity** [comment]
Se añadió la formula pero falta que se le aplique diseño CSS para que se vea bien.
