### ISSUE TITLE
INFORMACIÓN COMERCIAL

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#219]
El objeto del contrato en las experiencias debería ser con mas caracteres ya que al visualizarlo en Marketplace aparece cortado.

![image](https://cloud.githubusercontent.com/assets/9386020/7946107/66d938d0-093a-11e5-8cf5-b022e1b37a12.png)

**Comment by Josexandthecity** [comment]
Solucionado tanto en MP como en BO y en la base de datos.
