### ISSUE TITLE
Evaluación de desempeño Alpina

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#250]
al momento de darle siguiente en la evaluacion de desempeño me genera error.

![image](https://cloud.githubusercontent.com/assets/9558870/8316333/db477d94-19bb-11e5-8f1e-1f276f75a0c2.png)

**Comment by Josexandthecity** [comment]
Evaluacion de desempeño -> Ver Detalle -> Responder Preguntas (Click Siguiente)
