### ISSUE TITLE
Cámara de comercio backoffice

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#257]
En cámara de comercio tiene el campo razón social, por favor justificarlo que quede en todo el espacio y no como se muestra ahora.

![image](https://cloud.githubusercontent.com/assets/9558870/8317061/76046942-19c0-11e5-95ce-0b6e0838d474.png)

**Comment by andresbolivar** [comment]
listo..arreglado

**Comment by CarolinaLopez23** [comment]
Cerrado
