### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#273]
Eliminar las lineas que se encuentran en el recuadro rojo

![image](https://cloud.githubusercontent.com/assets/9386020/8968966/211a2798-3606-11e5-99da-059c40762b79.png)

**Comment by andresbolivar** [comment]
solucionado

**Comment by CarolinaLopez23** [comment]
Todavía siguen apareciendo.

**Comment by Josexandthecity** [comment]
Solucionado
