### ISSUE TITLE
Visualización 

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#277]
Debería aparecer solo los totales ya que el cliente esta realizando una comparación

TOTAL ACTIVO CORRIENTE
TOTAL ACTIVO NO CORRIENTE
TOTAL ACTIVO
TOTAL PASIVO CORRIENTE
TOTAL PASIVO NO CORRIENTE
TOTAL PASIVO 
TOTAL PATRIMONIO
TOTAL PASIVO + PATRIMONIO
INGRESOS OPERACIONALES
UTILIDAD BRUTA
UTILIDAD DEL EJERCICIO
EBITDA

![image](https://cloud.githubusercontent.com/assets/9386020/8969745/0069eaec-360b-11e5-8ba2-7392e99669e1.png)

**Comment by CarlosPinzon** [comment]
Prioridad 4
