### ISSUE TITLE
Modulo de comparación marketplace

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#283]
Poner en esta pantalla un ver detalle. Adicionar un campo que me diga la fecha de creación de la comparación.

![image](https://cloud.githubusercontent.com/assets/9558870/8984524/b273d496-3697-11e5-8d82-34e5ce13b0ef.png)

**Comment by CarlosPinzon** [comment]
Prioridad 3
