### ISSUE TITLE
Proceso de selección Marketplace

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#284]
Cambiar etiqueta de cerrar por iniciar proceso de selección.

![image](https://cloud.githubusercontent.com/assets/9558870/8985198/a0eb2126-369b-11e5-889b-bf3821c4fe71.png)

**Comment by Josexandthecity** [comment]
Solucionado!

**Comment by CarolinaLopez23** [comment]
Cerrado
