### ISSUE TITLE
NO CARGA ARCHIVO

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#295]
![image](https://cloud.githubusercontent.com/assets/10640094/9417530/c91c033a-4812-11e5-90db-c3457479447f.png)

No se puede subir un PDF de un Estado Financiero...

**Comment by Josexandthecity** [comment]
Se intentó replicar el error pero los archivos suben correctamente en cualquier proveedor, Es posible que se estuviera intentando subir un archivo de gran tamaño y por eso se presentara dicho error. Vamos a averiguar cual es el tamaño máximo permitido y se le informará al equipo de operaciones.
