### ISSUE TITLE
Actividad económica en experiencias.

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#296]
la palabra actividad económica no debe ir en este campo porque esta va sujeta al rut y los proveedores realizan diferentes actividades, debería ir solo la palabra Actividad.

![image](https://cloud.githubusercontent.com/assets/9558870/9497758/3528fff2-4bdc-11e5-9c92-2939b2f9b3d4.png)

**Comment by andresbolivar** [comment]
ya corregido
