### ISSUE TITLE
Proceso de selección 

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#297]
Debe decir Obra / proyecto / Proceso de selección

![image](https://cloud.githubusercontent.com/assets/9558870/9499945/14b821a6-4be8-11e5-96e3-d1f48931b818.png)

**Comment by CarolinaLopez23** [comment]
Sigue apareciendo

![image](https://cloud.githubusercontent.com/assets/9386020/9557523/5d97afd4-4da2-11e5-8259-d9248feb6254.png)

**Comment by andresbolivar** [comment]
solucionado
