### ISSUE TITLE
Proceso de selección-financiero

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#299]
Debe ir algo que me lleve al estado financiero como en todas las vistas.

![image](https://cloud.githubusercontent.com/assets/9558870/9506693/423cbc28-4c0f-11e5-8c4c-d3f5b0b48b99.png)

**Comment by Josexandthecity** [comment]
Se coloca un link para ver los estados financieros del proveedor
