### ISSUE TITLE
Mejora Consultas Listas Restrictivas

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#312]
modificar el texto de listas restrictivas, quitar el nombre del proveedor.

![image](https://cloud.githubusercontent.com/assets/9386020/9775783/97df4836-5717-11e5-95fa-ac8ac478ab51.png)

**Comment by Josexandthecity** [comment]
Ya fue implementado ese cambio
