### ISSUE TITLE
LISTAS RESTRICTIVAS 

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#313]
Cuando un proveedor aparece en listas restrictivas y este tiene tildes o Ñ se visualiza de la siguiente manera:

![image](https://cloud.githubusercontent.com/assets/9386020/9961583/cfa7201a-5de6-11e5-816f-cdb07ec06647.png)

**Comment by CarlosPinzon** [comment]
Prioridad 1
