### ISSUE TITLE
Reportes en Backoffice

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#319]
Poder realizar reportes en operaciones de los filtros:

1. Estados del proveedor: NIT, RAZÓN SOCIAL, TIPO DE IDENTIFICACIÓN, VALIDADOR
2. Fecha de ultima certificación: NIT, RAZÓN SOCIAL, TIPO DE IDENTIFICACIÓN, FECHA DE CERTIFICACIÓN.
2. Fecha vencimiento de cámaras de comercio.NIT, RAZÓN SOCIAL, TIPO DE IDENTIFICACIÓN, FECHA DE EXPEDICIÓN DEL CERTIFICADO.
3. Fecha vencimiento certificaciones: NIT, RAZÓN SOCIAL, TIPO DE IDENTIFICACIÓN, FECHA DE CADUCIDAD.

**Comment by CarlosPinzon** [comment]
Prioridad 2
