### ISSUE TITLE
Ciudad

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#323]
La ciudad aparece como Colombia, Magdalena, Cartagena. Debemos revisar este tema mas detallado ya que algunas ciudades están repetidas

![image](https://cloud.githubusercontent.com/assets/9386020/10179970/3475d0c2-66cf-11e5-9d55-5ae5465bbbf4.png)

**Comment by SebasDeveloper** [comment]
Recuerda que no es nuestra responsabilidad garantizar esta data, ya que nosotros no la ingresamos, sin embargo se realizó la verificación de la misma y se solucionaron muchas incoherencias que habían.
