### ISSUE TITLE
Resumen información HSEQ Marketplace

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#325]
El proveedor DESMARGINALIZAR SAS; en el resumen del proveedor en información HSEQ se visualiza     que el proveedor no cuenta con certificaciones de gestión ISO y al ver el detalle del proveedor este si cuenta con este documento y adicional a esto se muestra la guia RUC-CCS y el proveedor no cuenta con este documento.

DESMARGINALIZAR SAS
![image](https://cloud.githubusercontent.com/assets/9386020/10200647/3443c750-676d-11e5-8abe-763e6f62e455.png)

**Comment by Josexandthecity** [comment]
Solucionado
