### ISSUE TITLE
La moneda se esta cambiando a USD.

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#331]
![image](https://cloud.githubusercontent.com/assets/10640094/10313514/a9e0e568-6c15-11e5-9c44-e05b388ea8ce.png)

Revisando algunos valores de las experiencias que debían estar en pesos, ahora están apareciendo en dolares.

**Comment by Josexandthecity** [comment]
Se probo en Stage y desarrollo pero no se pudo replicar el error. Al crear o editar una experiencia en COP se guarda en COP y del mismo modo en el sentido contrario
