### ISSUE TITLE
Busqueda Marketplace

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#339]
Al momento de buscar un proveedor por razón social debería aparecer de primero el proveedor  buscado.

![image](https://cloud.githubusercontent.com/assets/9386020/10703938/fcef82f6-7998-11e5-93fd-50ef3b9aa9c8.png)

![image](https://cloud.githubusercontent.com/assets/9386020/10704028/97080d18-7999-11e5-87d0-19401217d7fa.png)

**Comment by CarlosPinzon** [comment]
Prioridad 2
