### ISSUE TITLE
Pantalla de Administración - Bancos 

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#348]
En la pantalla de administración en bancos esta apareciendo la maestra
![image](https://cloud.githubusercontent.com/assets/9386020/11628574/964cb488-9cc0-11e5-8673-1d394bc95c5d.png)

**Comment by Davidmt89** [comment]
se solucionó el problema con respecto al listado de bancos.
