### ISSUE TITLE
No guarda filtros

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#349]
Se actualiza cámara de comercio del proveedor NALSANI S.A.S Nit. 800020706, pero al hacer los filtros sigue apareciendo desactualizada la cámara.

![image](https://cloud.githubusercontent.com/assets/10758646/11632853/b2763b0a-9cd6-11e5-8cff-88bfd3b23b44.png)

![image](https://cloud.githubusercontent.com/assets/10758646/11632889/d281bfaa-9cd6-11e5-89f8-5716b487fd1c.png)

**Comment by Davidmt89** [comment]
se realizan los ajustes correspondientes a los filtros.
