### ISSUE TITLE
Pantalla de Administración - Geolocalización

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#351]
Al momento de crear una ciudad y darle guardar se crean varias campos en blanco

![image](https://cloud.githubusercontent.com/assets/9386020/11721985/7eb3e622-9f34-11e5-8d56-52d3be703733.png)

**Comment by Alex-JP** [comment]
Se dejo "No es capital" como parámetro de tipo ciudad predeterminado. al crear una ciudad se debe tener en cuenta seleccionar el pais, estado o depto previamente creado para asignar la ciudad.
