### ISSUE TITLE
No están apareciendo las ciudades.

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#352]
Al ingresar a la pestaña que corresponde a la información de Cámara de Comercio, las ciudades no están apareciendo. Si se ingresa la ciudad, al cambiar de pestaña no queda guardada.

![image](https://cloud.githubusercontent.com/assets/10640094/12126625/497cb8b2-b3c0-11e5-87c0-b7957a3cac55.png)

**Comment by Alex-JP** [comment]
Corregido

**Comment by SebasDeveloper** [comment]
se solucionó correctamente
