### ISSUE TITLE
Carga de listas Restrictivas

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#356]
Al cargar el archivo de listas restrictivas en el backoffice tarda mucho en ser validado y al ser consultado en marketplace ya esta validado.

**Comment by SebasDeveloper** [comment]
Se realiza la validación uno por uno, quiere decir que si se entra a marketplace y se encuentra un proveedor ya validado no quiere decir que ya terminó. El proceso de cargue y lectura de ese archivo es pesado, la demora es normal.

**Comment by CarlosPinzon** [comment]
El archivo nunca termina de cargar en backoffice, se verifican los proveedores en marketplace y si ya están validados se puede cerrar la ventana en backoffice.

**Comment by SebasDeveloper** [comment]
Vamos a realizar el proceso en conjunto con ustedes para evaluar el issue reportado

**Comment by SebasDeveloper** [comment]
Se soluciono correctamente
