### ISSUE TITLE
Búsqueda de proveedores en el gestor

### ISSUE THREAD

**Issue by CarolinaLopez23** [PublicarNuevosNegocios/ProveedoresOnLine#358]
Al momento de buscar el proveedor creado aparece dos veces en Publicar

![image](https://cloud.githubusercontent.com/assets/9386020/12762297/88bd76e4-c9bc-11e5-9e57-daed3e818577.png)

**Comment by Davidmt89** [comment]
Carolina, recuerda que el proveedor aparece con respecto a los formularios que tenga un comprador registrado, si el comprador relacionado en este caso publicar tiene dos formularios, el proveedor va a aparecer dos veces, por lo tanto esto no es un error como tal, cualquier inquietud me comentas!

**Comment by CarolinaLopez23** [comment]
Ok gracias
