### ISSUE TITLE
no sincroniza 

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#359]
No esta sincronizando 
![captura](https://cloud.githubusercontent.com/assets/9558768/12762863/50a15462-c9bf-11e5-9c5e-9a49c866d55e.PNG)
![captura2](https://cloud.githubusercontent.com/assets/9558768/12762870/57b79a54-c9bf-11e5-8b4c-498f9c195eb9.PNG)

**Comment by SebasDeveloper** [comment]
me regalas por favor la url
