### ISSUE TITLE
NO AVISA QUE SE CARGO DOCUMENTO NUEVO

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#360]
![image](https://cloud.githubusercontent.com/assets/10640094/12762807/068e4560-c9bf-11e5-99a8-d93a0ece9f2c.png)

Si se cargan varios documentos, el último nunca queda en rojo.

**Comment by SebasDeveloper** [comment]
Se realizó el proceso de cargar uno por uno y se verificó que quedara en rojo campo por campo, puedes validar nuevamente por favor
