### ISSUE TITLE
Creacion proveedores

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#371]
Al crear proveedores por cliente en el gestor no se esta viendo reflejado en backoffice. No queda asociado al cliente, solo a publicar.
![image](https://cloud.githubusercontent.com/assets/10758646/15967140/007cf986-2eec-11e6-9064-9fada2ed6576.png)

**Comment by SebasDeveloper** [comment]
Se solucionó correctamente
