### ISSUE TITLE
ERROR AL MOMENTO DE GUARDAR

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#372]
![image](https://cloud.githubusercontent.com/assets/10640094/16019850/d864da68-3170-11e6-8de9-09bfa84028ed

Para guardar en la grilla de personas de contacto sale error "object"

**Comment by AlePosso** [comment]
![image](https://cloud.githubusercontent.com/assets/10640094/16019924/39c8742c-3171-11e6-9cc9-88a475cfd8ab.png)

**Comment by DFZ-23** [comment]
Se soluciona el bug al guardar el registro de información de contacto
