### ISSUE TITLE
QUEDAN REPETIDOS

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#373]
![image](https://cloud.githubusercontent.com/assets/10640094/16019960/6180b722-3171-11e6-9074-4ffe9774ce26.png)

Cuando finalmente guarda, el contacto queda repetido y si se quiere ocultar alguno otra vez sale el error.

**Comment by DFZ-23** [comment]
Se resuelve el error, el error al guardar los registros ya no se duplican
