### ISSUE TITLE
No carga documentos

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#377]
En la cámara de comercio se tarda en guardar los miembros y al final sale el emergente en rojo "object". 
![c1](https://cloud.githubusercontent.com/assets/10758646/16166056/6a5f9d42-34ad-11e6-938d-fccf64bd00e0.PNG)
![c2](https://cloud.githubusercontent.com/assets/10758646/16166060/6dc5c614-34ad-11e6-91a6-282ef1a8fc69.PNG)

**Comment by SebasDeveloper** [comment]
Es un problema de latencia de red sin embargo se aumentaron los tiempos de respuesta para que la información no se pierda
