### ISSUE TITLE
Listas restrictivas

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#378]
Las listas restrictivas no se han corrido los últimos domingos (12 y 19 de junio) como se había fijado.

![image](https://cloud.githubusercontent.com/assets/10758646/16200338/8bbdf386-36d2-11e6-8712-3e3369f72211.png)

**Comment by SebasDeveloper** [comment]
ya se corrieron nuevamente y quedó solucionado el tema
