### ISSUE TITLE
No deja ver la vista preeliminar de este archivo 

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#38]
![image](https://cloud.githubusercontent.com/assets/9558615/5631099/d2ba902a-9591-11e4-811f-194eab44cc8a.png)

proveedor INSTRUCONTROLES LTDA. NIT 8002255830

**Comment by luixg11** [comment]
formulario polipropileno del caribe

**Comment by Davidmt89** [comment]
se realiza la modificación para que se pueda observar la preliminar del archivo.
