### ISSUE TITLE
Los proveedores ingresan información sin embargo no aceptan los términos y condiciones

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#39]
![image](https://cloud.githubusercontent.com/assets/9558615/5686369/40bd81ce-9810-11e4-8437-fead321fccc0.png)

En el anterior pantallazo se observa que el proveedor no está aceptando los términos y condiciones. El llenó el formulario, y cargó la respectiva información sin embargo no chulea, mi sugerencia es que esta pestaña no debería estar en el formulario sino que antes del formulario debería haber una pantalla donde ellos acepten términos y condiciones y si no lo aceptan no puedan continuar con el proceso.

El proveedor es GLOBAL SHIPPING AGENCIES S.A. NIT 8110010053, este formulario es el de Polipropileno del Caribe. Se puede observar que ellos si subieron información en el historial de cargue.

Saludos.

**Comment by SebasDeveloper** [comment]
Claro, que deberían aceptar los términos y condiciones, pero tiene que ser establecido campo obligatorio para que la información sea completa.
Sin embargo sugiero que para que no se presente este inconveniente, el punto de términos y condiciones debe estar en el principio del formulario para darle la importancia y la prioridad que requiere.
