### ISSUE TITLE
Backoffice - Cuando accedo al Menu de Compradores, aparecen registros tipo Proveedor

### ISSUE THREAD

**Issue by adrmunme** [PublicarNuevosNegocios/ProveedoresOnLine#42]
Backoffice - Cuando accedo al Menu de Compradores, aparecen registros tipo Proveedor

**Comment by SebasDeveloper** [comment]
Se está trabajando en este issue.

**Comment by SebasDeveloper** [comment]
la búsqueda de compradores aún no esta desarrollado por lo tanto esa vista que aparece es la misma vista de proveedores
