### ISSUE TITLE
Por qué al acceder al Menú Gestión Documental debo logearme otra vez?

### ISSUE THREAD

**Issue by adrmunme** [PublicarNuevosNegocios/ProveedoresOnLine#43]
No debería tener que logearme otra vez.

**Comment by SebasDeveloper** [comment]
Tienes razón, el problema era que estaba apuntando a otra url es decir de stg.Proveedoresonline.co/Backoffice 
a www.proveedoresonline.com/Registro.
Se solucionó el issue correctamente.
