### ISSUE TITLE
No aparece el link del historial

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#46]
![image](https://cloud.githubusercontent.com/assets/9558615/5828000/938dcb1e-a0cd-11e4-9e33-18f27c677b75.png)

Se comunica el proveedor a comunicar un problema se le solicita envíe correo con el pantallazo, por otra parte ingreso al proveedor, no me aparece el link del historial

**Comment by SebasDeveloper** [comment]
Por favor me regala la URL del proveedor el tipo y número de identificación para hacer el seguimiento gracias.

**Comment by luixg11** [comment]
8300666233 Steamcontrol de POLIPROPILENO DEL CARIBE

**Comment by SebasDeveloper** [comment]
![8300666233](https://cloud.githubusercontent.com/assets/7586207/5837045/b0771a56-a149-11e4-83b1-57a5393bbb40.png)

No encuentro el error, por favor validar la versión del navegador y verificar que el proveedor este realizando bien el proceso
