### ISSUE TITLE
Términos y condiciones no chuleados

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#47]
![image](https://cloud.githubusercontent.com/assets/9558615/5844748/50b8647c-a184-11e4-9802-01cbe7ce53f7.png)

Se repite el caso, el proveedor del pantallazo anexa la documentación, sin embargo en términos y condiciones no chulea.

STEAMCONTROL S.A. NIT 8300666233, Formulario Polipropileno

**Comment by SebasDeveloper** [comment]
Se realizó el ajuste con éxito, la mejora quedara expuesta en la próxima publicación.

**Comment by Davidmt89** [comment]
se realizó publicación del sitio con sus respectivas mejoras.
