### ISSUE TITLE
Información de Personas-Doc representante legal

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#50]
Al momento de seleccionar un archivo para adjuntarlo no permite seleccionar nada ni abre el espacio para agregar la imagen.

![image](https://cloud.githubusercontent.com/assets/9558870/5907300/df42d37c-a56b-11e4-875f-1c1bcb25e80e.png)

**Comment by Davidmt89** [comment]
no se permite continuar agregando información cuando hay reglas que no se cumplen, en este ejemplo el correo está mal escrito
