### ISSUE TITLE
Error al ingresar experiencias comerciales Bug

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#54]
![image](https://cloud.githubusercontent.com/assets/9558615/5907504/668da680-a56d-11e4-8fca-30f5b2566e0e.png)

Cuando en esta experiencia comercial estoy ingresando el valor, al momento de dar tab para saldar a el tipo de moneda, debería desplegar la opción sin embargo solo permite elegir una monera con el mouse.

Proveedor Transformadores Suntec

**Comment by luixg11** [comment]
Se sigue presentando el error.

![image](https://cloud.githubusercontent.com/assets/9558615/6080675/723c1bfc-ade1-11e4-837c-dee327e09a93.png)

**Comment by SebasDeveloper** [comment]
Se soluciono correctamente
