### ISSUE TITLE
No deja avanzar 

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#55]
Al momento de querer pasar de la pestaña de distribuidores no deja.
![image](https://cloud.githubusercontent.com/assets/9558768/5907550/d54baeaa-a56d-11e4-857d-2fca42af5273.png)
![image](https://cloud.githubusercontent.com/assets/9558768/5907601/24052b34-a56e-11e4-9856-2721d4006380.png)

**Comment by SebasDeveloper** [comment]
Lo que sucede es que estas haciendo click en un nombre de un menú no en una pantalla como tal.
