### ISSUE TITLE
Error al adjuntar experiencias

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#57]
![image](https://cloud.githubusercontent.com/assets/9558615/5907654/ab85cabe-a56e-11e4-844e-4d3309bb88f0.png)

Al momento de adjuntar un archivo cuando se está creando una experiencia comercial, se le da enter no abre ventana para elegir un documento y adjuntarlo simplemente sale seleccione el archivo

![image](https://cloud.githubusercontent.com/assets/9558615/5907672/e955be8a-a56e-11e4-852e-c4729a161ee4.png)

Solo permite seleccionar un archivo con el mouse.

**Comment by SebasDeveloper** [comment]
Recuerda que las acciones de la grilla son con la barra espaciadora
