### ISSUE TITLE
Error al momento de guardar una experiencia

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#59]
![image](https://cloud.githubusercontent.com/assets/9558615/5907694/1ac86a62-a56f-11e4-8db0-2f863d5c542b.png)

Al momento de guardar una experiencia arroja un mensaje de error, se valida y toda la información está completa.

**Comment by Davidmt89** [comment]
el error se genera al no escribir una actividad económica personalizada, la cual ya se encuentra reportada como bug, por lo tanto este bug se soluciona con el otro registrado.
