### ISSUE TITLE
Error al momento de guardar una experiencia 2

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#61]
![image](https://cloud.githubusercontent.com/assets/9558615/5907743/7aa16290-a56f-11e4-987f-b1be4ac2feda.png)

Se identifica que solo guarda la experiencia cuando se le asigna una actividad económica personalizada. Esto no debería ser obligatorio en todos los proveedores.

**Comment by Davidmt89** [comment]
Se realizaron las respectivas modificaciones para que deje ingresar una experiencia sin que sea obligatorio una actividad económica personalizada.
