### ISSUE TITLE
Sistema de riesgos laborales

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#62]
en el espacio de sistema de riesgos laborales no registra la formula de LTIF, y en ninguno de los campos deja guardar con el botón de siguiente.

![image](https://cloud.githubusercontent.com/assets/9558870/5907822/207d2faa-a570-11e4-95ae-33e537e5e2c9.png)

**Comment by Davidmt89** [comment]
se modifica la formula para que se vea el resultado apenas se guarde la información de la grilla y se habilita los botones de siguiente y anterior para que guarde toda la información.
