### ISSUE TITLE
fechas

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#64]
Deja guardar fechas incoherentes.
![image](https://cloud.githubusercontent.com/assets/9558768/5907859/6d0b34de-a570-11e4-9d76-1699a6b1a2b5.png)

**Comment by SebasDeveloper** [comment]
La información suministrada es responsabilidad directa de quien maneja la herramienta, es decir no puedo controlar un rango de fechas.
