### ISSUE TITLE
Error al adjuntar archivos de salud y medio ambiente

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#65]
![image](https://cloud.githubusercontent.com/assets/9558615/5907871/8d0aa0da-a570-11e4-8aba-d9ad32e49129.png)

Se presenta el mismo error de adjuntar archivos, al apretar la tecla enter no arroja para elegir el archivo, solo lo deja hacer manualmente, es decir, con el mouse.

**Comment by SebasDeveloper** [comment]
Voy a dejarlo como una mejora, porque si te fijas, al momento de pararte con el mouse o con el teclado sobre la celda del archivo, inmediatamente te da la opción de cargar un nuevo archivo, la única manera de ver el archivo es haciendo click en el link.
