### ISSUE TITLE
estados financieros

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#67]
deja ingresar cualquier cantidad.
![image](https://cloud.githubusercontent.com/assets/9558768/5907998/ae7f4396-a571-11e4-8b07-1a0d7438d78a.png)

**Comment by SebasDeveloper** [comment]
Recuerda que esta pantalla aun esta en desarrollo, sin embargo la voy a dejar como una mejora
