### ISSUE TITLE
ERROR EXPERIENCIAS

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#68]
![image](https://cloud.githubusercontent.com/assets/10640094/5907977/877728e0-a571-11e4-95a9-dbdb67ab1c13.png)

En el momento de mirar de nuevo la pestaña de experiencias, se demora en cargar mucho la información.

**Comment by SebasDeveloper** [comment]
ten en cuenta la red está molestando
