### ISSUE TITLE
NO GUARDA ARCHIVO

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#69]
![image](https://cloud.githubusercontent.com/assets/10640094/5908176/31af1fec-a573-11e4-89c4-af144153819c.png)

No queda guardado el archivo del certificado de la ARL.

**Comment by SebasDeveloper** [comment]
si lo guardó, si te fijas cuando aparece el link de VerArchivo es porque si lo guardó.
