### ISSUE TITLE
Error Estados Financieros

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#70]
![image](https://cloud.githubusercontent.com/assets/9558615/5908377/ec3ef5a2-a574-11e4-9e11-3f06cc853740.png)

En Estados Financieros se denotan tres errores,

El primero es que permite ingresar cualquier valor y guardarlo.

Despues de haber guardado los valores ya mencionados, cambia los valores, en el pantallazo adjunto se muestra de disponible un valor 79691 cuando en realidad el valor que se ingresó fue de $159,382,390.

El tercer error es que calcula una sumatoria que permite tener un subtotal pero esta sumatoria está errada porque no aplica las formulas que se aplican en los estados financieros.

**Comment by SebasDeveloper** [comment]
Claro, tienes razón pero recuerda que es una pantalla que aún esta en desarrollo
