### ISSUE TITLE
Error Diseño Estados Financieros 

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#72]
![image](https://cloud.githubusercontent.com/assets/9558615/5908507/2da70a60-a576-11e4-8616-acf9bc24eb08.png)

Como se puede observar en el pantallazo adjunto, se observa que los rubros INGRESOS OPERACIONALES Y COSTOS DE VENTAS están repetidos, por otra parte como ya se reportó en un error anterior, los valores suman, pero en la ecuación contable deberían haber una operación de diferencia.

Además, en los rubros que están repetidos cuando uno intenta escribir una cifra, inmediatamente se le da tab para avanzar, el valor regresa a 0.

![image](https://cloud.githubusercontent.com/assets/9558615/5908529/891f89ee-a576-11e4-931e-a86de433093b.png)

![image](https://cloud.githubusercontent.com/assets/9558615/5908531/8eb93eb8-a576-11e4-9643-3a9aff8d7049.png)

**Comment by SebasDeveloper** [comment]
Recuerda que está pantalla aún no está terminada, sin embargo la voy a dejar como una mejora.
