### ISSUE TITLE
OPCION VER ARCHIVO

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#73]
![image](https://cloud.githubusercontent.com/assets/10640094/5908827/f50a628a-a578-11e4-9c63-b2d64d553587.png)

Al dar enter sobre la opción de "ver archivo" con el teclado, no se puede subir imagen, solo se puede con el mouse.

**Comment by Davidmt89** [comment]
para acceder al campo "ver archivo" se debe presionar la tecla barra espaciadora.
