### ISSUE TITLE
Error al guardar experiencias

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#74]
![image](https://cloud.githubusercontent.com/assets/9558615/5908991/4d115528-a57a-11e4-8226-0623f570544a.png)

Las experiencias se repitieron sin yo crear una nueva, fue al darle clik en guardar?

**Comment by Davidmt89** [comment]
se soluciona el problema de inserción de datos en las experiencias comerciales.
