### ISSUE TITLE
NO GUARDA INFORMACIÓN DE CÁMARA DE COMERCIO

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#76]
![image](https://cloud.githubusercontent.com/assets/10640094/5909158/f4119cd8-a57b-11e4-8d1d-15cde004155c.png)

No guarda archivo y tampoco información de los miembros de la junta directiva.

**Comment by Davidmt89** [comment]
se solucionó el problema
