### ISSUE TITLE
Error Cámara de Comercio

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#78]
![image](https://cloud.githubusercontent.com/assets/9558615/5909297/3d5f8b24-a57d-11e4-8d49-99b35e5c5a85.png)

Acabo de darle click en guardar y no guardó la información de la cámara de comercio

**Comment by Davidmt89** [comment]
se solucionó el problema de la vista de cámara de comercio.
