### ISSUE TITLE
Error seguimientos

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#79]
![image](https://cloud.githubusercontent.com/assets/9558615/5909568/e61f2542-a57f-11e4-88fa-127e195e3c7d.png)

Al tratar de crear un seguimiento y comprador no me carga. Le doy click pero no me carga nada.

**Comment by SebasDeveloper** [comment]
Recuerda que la pantalla aun no está terminada, en el próximo paso de versión se puede revisar completamente.

Saludos
