### ISSUE TITLE
SEGUIMIENTOS

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#80]
![image](https://cloud.githubusercontent.com/assets/10640094/5909625/59e563c4-a580-11e4-8e0c-0aa00cdd4be4.png)

No se puede agregar un seguimiento.

**Comment by SebasDeveloper** [comment]
Recuerda que esto puede ser una mejora, dado que se mencionó que la pantalla no está terminada.
Gracias por el aporte.
