### ISSUE TITLE
Error en el módulo de gestión documental

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#81]
![image](https://cloud.githubusercontent.com/assets/9558615/5939627/594fc2c0-a6d3-11e4-96fc-5a279f6d8f15.png)

Cuando ingreso al proveedor APPLEX S.A.S. NIT 8301377538 en su pestaña de Estados Financieros, aparece este error.

**Comment by Davidmt89** [comment]
se solucionó el problema del proveedor APPLEX S.A.S
