### ISSUE TITLE
SUGERENCIA EN INFO DE CONTACTO DE LA EMPRESA

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#82]
![image](https://cloud.githubusercontent.com/assets/10640094/5959451/6ee9830e-a79c-11e4-996b-9ea206ce6317.png)
![image](https://cloud.githubusercontent.com/assets/10640094/5959382/c139df9c-a79b-11e4-8700-2f109b28ae15.png)

Sería bueno que los campos fueran parecidos a los de información básica y llenarlos de acuerdo a la información que se tenga como teléfonos, correos, paginas web, etc.

**Comment by SebasDeveloper** [comment]
De ser así no se podrían tener varios contactos, el propósito real de la grilla es permitir crear muchos registro de forma ordenada.
