### ISSUE TITLE
Mejora al intentar crear un contacto

### ISSUE THREAD

**Issue by luixg11** [PublicarNuevosNegocios/ProveedoresOnLine#83]
![image](https://cloud.githubusercontent.com/assets/9558615/5959531/195077a8-a79d-11e4-9cfb-495abc08973b.png)

Existen contactos como el siguiente: 
![image](https://cloud.githubusercontent.com/assets/9558615/5959549/39f9ff88-a79d-11e4-8274-a8bb850ff1a9.png)

Se puede observar que en el módulo de gestión documental, el proveedor NO escribió el número de cédula. Debería dejar seguir sin seleccionar cédula o pasaporte o el documento que sea porque ese espacio no nos discriminaron información.

**Comment by luixg11** [comment]
![image](https://cloud.githubusercontent.com/assets/9558615/5959842/623380e4-a79f-11e4-91af-71da4acbf85d.png)
Este error se deriva de la mejora anterior

**Comment by Davidmt89** [comment]
se modifican las validaciones de la vista para que deje continuar con los demás campos.
