### ISSUE TITLE
No guarda la información

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#87]
No guarda la información:
Información diligenciada
![image](https://cloud.githubusercontent.com/assets/9558768/5960084/0fca5376-a7a1-11e4-8867-ddb766626935.png)
 
![image](https://cloud.githubusercontent.com/assets/9558768/5960108/3f18ac90-a7a1-11e4-82a0-8f60e093290e.png)

**Comment by SebasDeveloper** [comment]
No pude replicar el error.
