### ISSUE TITLE
Información contacto

### ISSUE THREAD

**Issue by DianaTibata** [PublicarNuevosNegocios/ProveedoresOnLine#88]
En el campo Información contacto de la empresa debería permitir que en el  momento de crear un campo deje ingresar toda la información en un solo nombre ya que es la información de la empresa y esa no tiene mas nombres si no la razón social, o permitir ingresar mas info sin que sea obligatorio el campo nombre.

![image](https://cloud.githubusercontent.com/assets/9558870/5960118/4769f750-a7a1-11e4-9781-d2cd70ebac03.png)

**Comment by SebasDeveloper** [comment]
El campo nombre en todas las pantallas de replantearán la próxima semana
