### ISSUE TITLE
OPCIÓN PARA ELIMINAR

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#90]
![image](https://cloud.githubusercontent.com/assets/10640094/5960365/d2c59920-a7a2-11e4-90a3-35a7a317219c.png)

Debería haber una opción para eliminar registros, hay una que dice Descartar pero esta no elimina nada.

**Comment by Davidmt89** [comment]
se va a replantear la opción de borrado de los campos.
