### ISSUE TITLE
Sugerencia experiencias

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#92]
Me parece inoficiosa la pestaña "NOMBRE" primero porque es confuso a lo que hace referencia y segundo porque en las demás pestañas esta muy claro lo que necesitamos.

**Comment by luixg11** [comment]
![image](https://cloud.githubusercontent.com/assets/9558615/5961193/e0845ac8-a7a8-11e4-8778-69a3ecf20c86.png)

Complemento esta sugerencia ya que es redundante.

**Comment by Davidmt89** [comment]
se va a replantear todos los campos de nombres.
