### ISSUE TITLE
Error en experiencias

### ISSUE THREAD

**Issue by CarlosPinzon** [PublicarNuevosNegocios/ProveedoresOnLine#93]
En la pestaña que sigue después de "OBJETO DEL CONTRATO" falta agregar una "A" a la palabra "MESTRA ESTANDAR".  
*** "NO ME DEJA PEGAR LOS PANTALLAZOS EN LOS COMENTARIOS"****

**Comment by Davidmt89** [comment]
se corrigen los títulos de Maestras
