### ISSUE TITLE
Menú

### ISSUE THREAD

**Issue by johanalemos** [PublicarNuevosNegocios/ProveedoresOnLine#94]
Me parece que el menú no debería verse así.

![image](https://cloud.githubusercontent.com/assets/9558768/5961118/4910a84a-a7a8-11e4-9ed2-db39ed5762f0.png)

**Comment by Davidmt89** [comment]
para ingresar al sistema previamente se debe iniciar sesión, este problema puede presentarse por que no se ha iniciado sesión.
