### ISSUE TITLE
SUGERENCIA

### ISSUE THREAD

**Issue by AlePosso** [PublicarNuevosNegocios/ProveedoresOnLine#97]
![image](https://cloud.githubusercontent.com/assets/10640094/5961356/1bc2c3b2-a7aa-11e4-81ab-f85c7f8fa2ec.png)

En la parte de la información de cámara de comercio se podría insertar una lista desplegable en el campo de cargo de los miembros de la junta directiva, socios etc.

**Comment by SebasDeveloper** [comment]
No tenemos conocimiento de las personas ni los cargos que pertenecen al a junta.
